import pydantic


class Table2Roles(pydantic.BaseModel):
    category: list[str] = []
    subcategory: list[str] = []
    hierarchy: list[str] = []
    title: list[str] = []
    variants: list[str] = []
    compass_class: list[str] = []
    line_manager: list[str] = []
    approval_process: list[str] = []
    approver: list[str] = []
    relevant: list[str] = []
    induction: list[str] = []
    membership: list[str] = []
    trustee: list[str] = []
    disclosure: list[str] = []
    review: list[str] = []
    location_england: list[bool] = []
    location_scotland: list[bool] = []
    location_northern_ireland: list[bool] = []
    location_wales: list[bool] = []
    location_bso: list[bool] = []
    location_branches: list[bool] = []
    location_guernsey: list[bool] = []
    location_jersey: list[bool] = []
    location_headquarters: list[bool] = []
    location_uk_contingent: list[bool] = []
    module_1: list[str] = []
    module_trustee_introduction: list[str] = []
    module_2: list[str] = []
    module_3: list[str] = []
    module_4: list[str] = []
    module_safety: list[str] = []
    module_safeguarding: list[str] = []
    module_gdpr: list[str] = []
    module_section_wood_badge: list[str] = []
    training_deadline: list[str] = []
    module_ms_wood_badge: list[str] = []
    module_first_aid_certificate: list[str] = []
    module_7: list[str] = []
    module_24: list[str] = []
    module_25: list[str] = []
    module_30: list[str] = []
    module_37: list[str] = []
